include: package:pedantic/analysis_options.yaml

analyzer:
  exclude:
    [
      build/**,
      lib/**/*.g.dart,
      lib/config/*.dart,
      lib/helpers/*.dart,
      lib/models/**/*.dart,
      lib/providers/*.dart,
    ]
  strong-mode:
    implicit-casts: true
    implicit-dynamic: true
    # Explanation: https://www.reddit.com/r/FlutterDev/comments/eb546t/tighten_up_you_type_checking_in_preparation_of/
  errors:
    # treat missing required parameters as an error (not a hint)
    missing_required_param: error
    # treat missing returns as an error (not a hint)
    missing_return: error
