name: ceras
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+32

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1
  provider: ^4.3.2+1
  intl: ^0.16.1
  dio: ^3.0.10
  package_info: ^0.4.3
  device_info: ^0.4.2+7
  shared_preferences: ^0.5.10
  json_annotation: ^3.0.1
  progress_dialog: ^1.2.4
  cupertino_icons: ^0.1.3
  flutter_blue: ^0.7.2
  permission_handler: "^5.0.1+1"
  permission_handler_platform_interface: "2.0.1"
  #background_fetch: "^0.6.0"
  flutter_inappwebview: ^4.0.0+4
  url_launcher: ^5.5.0
  launch_review: ^2.0.0
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.4+1
  firebase_dynamic_links: ^0.6.0
  firebase_performance: ^0.4.0
  firebase_messaging: ^7.0.0
  firebase_in_app_messaging: ^0.2.0+1

dev_dependencies:
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.7.5
  json_serializable: ^3.4.0
  build_runner: ^1.10.0

  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - i18n/
    - assets/privacy/index.html
    - assets/images/placeholder.jpg
    - assets/images/location.png
    - assets/images/camera.png
    - assets/images/push_notification.png
    - assets/images/ceraswithletter.png
    - assets/images/Picture1.jpg
    - assets/images/Picture2.jpg
    - assets/images/condition.png
    - assets/images/bluetooth.png
    - assets/images/devicenotfound.png
    - assets/images/health.png
    - assets/images/connected.png
    - assets/images/support.png
    - assets/images/t&c.png
    - assets/images/emptyImage.png

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Bold.ttf
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 400

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "dev_assets/icon.png"
  adaptive_icon_background: #c00000
